### ISSUE TITLE
`Operation not permitted` when cron tries to execute script

### ISSUE THREAD

**Issue by pnadolny13** [meltano/cron-ext#45]
I'm getting this error message when my cron executes:

```/bin/sh: /Users/pnadolny/Documents/Git/GitHub/meltano/squared/data/.meltano/run/cron-ext/spreadsheets_anywhere_el.sh: Operation not permitted```

It might be user error but I did make sure the permissions were updated to allow it to be executed. Is there any step I'm missing?

cc @WillDaSilva

**Comment by WillDaSilva** [comment]
@pnadolny13 Could this be an issue because you're running on macOS?

https://apple.stackexchange.com/questions/378553/crontab-operation-not-permitted

**Comment by pnadolny13** [comment]
@WillDaSilva that was exactly it! Thanks for the link.
